pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'smart-expense-tracker'
        DOCKER_TAG = "${BUILD_NUMBER}"
        CONTAINER_NAME = 'expense-tracker-container'
        APP_PORT = '5001'   // changed to avoid port conflict
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat '"C:\\Program Files\\Python314\\python.exe" -m pip install -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                bat '"C:\\Program Files\\Python314\\python.exe" -c "import flask; print(\'Flask imported successfully\')"'
            }
        }

        stage('Docker Build') {
            steps {
                bat '''
                docker build -t %DOCKER_IMAGE%:%DOCKER_TAG% .
                docker tag %DOCKER_IMAGE%:%DOCKER_TAG% %DOCKER_IMAGE%:latest
                '''
            }
        }

        stage('Cleanup Old Containers') {
            steps {
                bat '''
                docker rm -f %CONTAINER_NAME% || exit 0
                '''
            }
        }

        stage('Deploy') {
            steps {
                bat '''
                docker run -d --name %CONTAINER_NAME% -p %APP_PORT%:5000 %DOCKER_IMAGE%:latest
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                bat 'docker ps'
            }
        }
    }
}